### ISSUE TITLE
Bin file selection box opens Explorer window only

### ISSUE THREAD

**Issue by Budman1758** [Grovkillen/ESP_Easy_Flasher#6] opened 2018-05-06 18:15 UTC
I'm sure you are probably aware of this but it would be nice if the open folder button allowed you to navigate to and select the folder and file you want. Now it only opens a new explorer window. 

Not a big deal. Just thought I'd put this here so you can prioritize it for future improvement.

**Comment by Grovkillen** [comment] 2018-07-16 08:06
This is by design since I want my app to be totally portable. The open folder is only to let you drop your bin files there. Is this a bad idea from many users perspective I might change it... 👍

**Comment by Grovkillen** [comment] 2018-12-09 19:33
Okay, I will close this one. It opens the bin folder because it's part of the release zip now.

**Closed as completed by Grovkillen** 2018-12-09 19:33 UTC
